name: Publish

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'


      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release -m Cargo.toml
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./target/wheels/*.whl

